- Configuration/App/App-Base.xcconfig
https://netguru.atlassian.net/browse/BM-523
Fixed entitlements path
> [BM-523] Fix staging bitrise build

- Baby Monitor.xcodeproj/project.pbxproj
- Configuration/App/App-Base.xcconfig
- Podfile
- Podfile.lock
https://netguru.atlassian.net/browse/BM-516
Configured Crashlytics for a project.
> [BM-516] Configure Crashlytics

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Supporting Files/Firebase/Staging/GoogleService-Info.plist
https://netguru.atlassian.net/browse/BM-516
Updated Crashlytics configuration
> [BM-516] Crashlytics

- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Services/MediaPlayer/MicrophoneFactory.swift
- Baby Monitor/Source Files/Services/MediaPlayer/NodeCapture.swift
- Podfile
- Podfile.lock
https://netguru.atlassian.net/browse/BM-536
Application crashed on iOS 13 when entering the streaming view on baby device.
It has been probably because of the AudioKit graph with loose (not connected on both sides) nodes and not closing the AudioKit session before opening another one.
> [BM-536] Rework the logic of microphone recording

- Baby Monitor/Resources/Constants.swift
https://netguru.atlassian.net/browse/BM-540
Change a constant for notification limit.
> [BM-540] Set a 3 minutes time limit for notifications

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Resources/Constants.swift
- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Modules/Onboarding/ClientSetupOnboardingViewModel.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/OnboardingClientSetupViewController.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/OnboardingPairingCoordinator.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/OnboardingSpinnerView.swift
- Baby Monitor/Source Files/Services/Errors/ServerErrorLogger.swift
- Baby Monitor/Source Files/Services/NetService/NetServiceClient.swift
- Baby Monitor/Source Files/Services/NetService/NetServiceServer.swift
- Baby MonitorTests/Mocks/ServerErrorLoggerMock.swift
- Baby MonitorTests/Modules/ClientSetup/ClientSetupViewModelTests.swift
https://netguru.atlassian.net/browse/BM-566
- Added cancel button to the pairing screen, so the user won't be blocked with no option to return from the screen
- Increased the timeout time
- Added logging errors to Crahlytics
> [BM-566] Update searching for device logic

- README.md
- bitrise.yml
https://netguru.atlassian.net/browse/BM-551
Migrated to App Center.
> [BM-551] Migrate from HockeyApp to AppCenter

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Extensions/Bundle+BuildNumber.swift
- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Modules/Settings/BaseSettingsView.swift
- Baby Monitor/Source Files/Modules/Settings/ParentSettingsView.swift
- Baby Monitor/Source Files/Modules/Settings/ParentSettingsViewController.swift
- Baby Monitor/Source Files/Modules/Settings/ServerSettingsView.swift
- Baby Monitor/Source Files/Modules/Settings/ServerSettingsViewController.swift
- Baby Monitor/Source Files/Modules/Settings/SettingsCoordinator.swift
- Baby Monitor/Source Files/Utils/AppVersionProvider.swift
https://netguru.atlassian.net/browse/BM-577
Fix app version number shown on settings views
-
> BM-577 Fix app version number on settings views

- Baby Monitor/Source Files/Custom Views/StreamVideoView.swift
- README.md
https://netguru.atlassian.net/browse/BM-577
Fixed the stretching video stream by setting scaleAspectFill mode. Additionally, update to the view which uses Metal framework underhood. Removed unneeded constraints.
> [BM-577] Add video transform for different screen sizes

- Baby Monitor/Source Files/Modules/Server/ServerViewController.swift
- Baby Monitor/Source Files/Modules/Server/ServerViewModel.swift
- Baby Monitor/Source Files/Services/CryingDetection/CryingDetectionService.swift
- Baby Monitor/Source Files/Services/CryingDetection/CryingEventService.swift
- Baby Monitor/Source Files/Services/Networking/NetworkDispatcher.swift
- Baby Monitor/Source Files/Services/Notifications/NotificationService.swift
- Baby Monitor/Source Files/Services/ServerService.swift
- Baby MonitorTests/Mocks/CryingDetectionServiceMock.swift
- Baby MonitorTests/Mocks/CryingEventsServiceMock.swift
https://netguru.atlassian.net/browse/BM-581
Added label to a baby server view with debugging info about crying detection and push notifications request sending.
> [BM-581] Add debugging info to a view

- Baby Monitor/Source Files/Modules/Dashboard/DashboardViewModel.swift
- Baby Monitor/Source Files/Modules/Onboarding/ClientSetupOnboardingViewModel.swift
- Dependencies/WebRTC/WebRtcClientManager.swift
- Dependencies/WebRTC/WebRtcServerManager.swift
https://netguru.atlassian.net/browse/BM-445
Unification of communication setup and parameters between iOS and Android devices
> BM-445 Unify devices communication between iOS and Android

- Baby Monitor/Source Files/Services/Networking/NetworkDispatcher.swift
https://netguru.atlassian.net/browse/BM-581
Resolved json parsing error.
> [BM-581] Debug view update

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Models/ClearableLazyItem.swift
- Baby Monitor/Source Files/Modules/CameraPreview/CameraPreviewViewController.swift
- Baby Monitor/Source Files/Modules/CameraPreview/CameraPreviewViewModel.swift
- Baby Monitor/Source Files/Modules/Dashboard/DashboardCoordinator.swift
- Baby Monitor/Source Files/Modules/Dashboard/DashboardViewModel.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/OnboardingPairingCoordinator.swift
- Baby Monitor/Source Files/Modules/Server/ServerCoordinator.swift
- Baby Monitor/Source Files/Modules/Settings/SettingsCoordinator.swift
- Baby Monitor/Source Files/Services/Connection/SocketCommunicationManager.swift
- Baby Monitor/Source Files/Services/Persistence/BabyModelControllerProtocol.swift
- Baby Monitor/Source Files/Services/Persistence/MemoryCleaner.swift
- Baby Monitor/Source Files/Services/Reset/ApplicationResetter.swift
- Baby Monitor/Source Files/Services/Websocket/Messages/MessageStreamProtocol.swift
- Baby Monitor/Source Files/Services/Websocket/WebSocketEventMessageService.swift
- Baby Monitor/Source Files/Services/Websocket/WebSocketProtocol.swift
- Baby Monitor/Source Files/Services/Websocket/WebSocketWebRtcService.swift
- Baby MonitorTests/Mocks/MemoryCleanerProtocolMock.swift
- Baby MonitorTests/Mocks/NotificationServiceProtocolMock.swift
- Baby MonitorTests/Mocks/WebSocketWebRtcServiceMock.swift
- Baby MonitorTests/Modules/App Reset/ApplicationResetterTests.swift
- Baby MonitorTests/Modules/Communication/SocketCommunicationManagerTests.swift
https://netguru.atlassian.net/browse/BM-661
Fix reset and reestablishing communication between devices
> [BM-561] Fix reset and reestablishing communication between devices

- bitrise.yml
https://netguru.atlassian.net/browse/BM-594
> [BM-594] Add JIRA transition step

- Baby Monitor/Source Files/Services/MediaPlayer/MicrophoneFactory.swift
https://netguru.atlassian.net/browse/BM-560
Fix sampling rate mismatch crash on initialising AudioKit session
> [BM-560] Fix AudioKit session crash on Baby app init

- Baby Monitor/Source Files/Services/MediaPlayer/MicrophoneFactory.swift
Reverts netguru/baby-monitor-client-ios#169
> Revert "[BM-560] Fix AudioKit session crash on Baby app init"

- Baby Monitor/Resources/Constants.swift
- Baby Monitor/Source Files/Services/CryingDetection/AudioMicrophoneService.swift
https://netguru.atlassian.net/browse/BM-598
Limited sending sounds for recognition to ML model
> [BM-598] Recognise baby crying each 10 sec

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Source Files/AppDelegate.swift
- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Modules/RootCoordinator.swift
- Baby Monitor/Source Files/Modules/Server/ServerViewModel.swift
- Baby Monitor/Source Files/Other Protocols/Coordinator.swift
- Baby Monitor/Source Files/Services/MediaPlayer/NodeCapture.swift
- Baby Monitor/Source Files/Services/Reset/ApplicationResetter.swift
- Baby MonitorTests/Mocks/ServerServiceMock.swift
- Baby MonitorTests/Modules/App Reset/ApplicationResetterTests.swift
- Podfile
- Podfile.lock
https://netguru.atlassian.net/browse/BM-599
The microphone was sometimes not working after:
- app reset
- app termination
Now it should be fixed.
Additionally, a bug with a reset after the first time is also fixed. (It was influencing saving baby cries to data base).
> [BM-599] AudioKit sometimes doesn't restart after reset

- LICENSE
https://netguru.atlassian.net/browse/BM-611
> [BM-611] Add license

- Baby Monitor/Source Files/Services/NetService/NetServiceServer.swift
https://netguru.atlassian.net/browse/BM-611
Fixed adding a device name.
> [BM-611] Fix setting device name

- Baby Monitor/Source Files/Modules/Settings/ParentSettingsView.swift
- Baby Monitor/Source Files/Modules/Settings/ParentSettingsViewModel.swift
- Baby Monitor/Source Files/Modules/Settings/SettingsCoordinator.swift
https://netguru.atlassian.net/browse/BM-541
Fixed presenting action sheet alert on iPad so it would not crash
> [BM-541] Parent device - app crash on iPad after attempt to take a photo of the baby in the settings screen

- Baby Monitor/Source Files/Modules/Onboarding/Pairing/Multiple Devices/Code/OnboardingCompareCodeViewModel.swift
https://netguru.atlassian.net/browse/BM-612
Fix wrong conversion from Int to String.
> [BM-612] Code verification updates

- Baby Monitor/Source Files/Services/CryingDetection/AudioMicrophoneService.swift
- Baby Monitor/Source Files/Services/CryingDetection/CryingEventService.swift
- Baby Monitor/Source Files/Services/MediaPlayer/MicrophoneFactory.swift
- Baby Monitor/Source Files/Services/MediaPlayer/NodeCapture.swift
- Baby MonitorTests/Mocks/MicrophoneRecordMock.swift
https://netguru.atlassian.net/browse/BM-602
Fixed sending recordings to Firebase by updating the configuration of the audio.
> [BM-602] iOS doesn't seem to send recordings to firebase

- Gemfile
- Gemfile.lock
Added missing plugin for appcenter.
> Added missing plugin to Highway

- Gemfile
- Gemfile.lock
> Updated Highway

- Baby Monitor/Source Files/Modules/Dashboard/DashboardViewModel.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/Multiple Devices/Code/OnboardingCompareCodeViewModel.swift
- Baby Monitor/Source Files/Modules/Server/ServerCoordinator.swift
- Baby Monitor/Source Files/Services/Reset/ApplicationResetter.swift
- Baby Monitor/Source Files/Services/ServerService.swift
- Baby Monitor/Source Files/Services/Websocket/Models/EventMessage.swift
- Baby Monitor/Source Files/Services/Websocket/WebSocketEventMessageService.swift
- Baby MonitorTests/Modules/App Reset/ApplicationResetterTests.swift
- Baby MonitorTests/Modules/ClientSetup/OnboardingCompareCodeViewModelTests.swift
https://netguru.atlassian.net/browse/BM-638
Update the EventMessage structure
> [BM-638] Unify sending events Android - iOS

- Gemfile
- Gemfile.lock
- Highwayfile.yml
- bitrise.yml
Highway configuration for `release/*` branch.
> Configured highway for release branch

- Highwayfile.yml
https://netguru.atlassian.net/browse/BM-
Release builds will be prepared now with bitrise build number.
> [Highway] Release build number set to bitrise build number

- Gemfile
- Highwayfile.yml
https://netguru.atlassian.net/browse/BM-
I've changed Highway version and added team name to steps.
> [Highway] Small improvements

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Extensions/UserDefaults+Onboarding.swift
- Baby Monitor/Source Files/Modules/Dashboard/DashboardCoordinator.swift
- Baby Monitor/Source Files/Modules/Onboarding/OnboardingCoordinator.swift
- Baby Monitor/Source Files/Modules/Onboarding/Specify Device/Info/SpecifyDeviceInfoOnboardingView.swift
- Baby Monitor/Source Files/Modules/Onboarding/Specify Device/Info/SpecifyDeviceInfoOnboardingViewController.swift
- Baby Monitor/Source Files/Modules/Onboarding/Specify Device/Info/SpecifyDeviceInfoOnboardingViewModel.swift
https://netguru.atlassian.net/browse/BM-615
Disabled onboarding after the first start and removed the back button from the next screen at all.
> [BM-615] Disable Onboarding after first app start

- Baby Monitor.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
https://netguru.atlassian.net/browse/BM-657
This is a test build (needed for QA) which will be reverted in the next PR.
> [BM-657] Enable debug view on staging

- Baby Monitor.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme
Reverts netguru/baby-monitor-client-ios#203
> Revert "[BM-657] Enable debug view on staging"

- README.md
https://netguru.atlassian.net/browse/BM-659
Update Xcode and Pods versions in README.md.
> [BM-659] Update Xcode version in README.md

- Baby Monitor/Source Files/Services/Websocket/Models/EventMessage.swift
https://netguru.atlassian.net/browse/BM-626
Updated the key to be the same as on Android.
> [BM-626] Fix: Add WebRtc stream basic error handling

- Baby Monitor/Source Files/Modules/Onboarding/Pairing/Multiple Devices/Code/OnboardingCompareCodeViewModel.swift
- Baby Monitor/Source Files/Services/SoundDetection/SoundDetectionMode.swift
- Baby Monitor/Source Files/Services/Websocket/Models/EventMessage.swift
- Baby Monitor/Source Files/Services/Websocket/WebSocketEventMessageService.swift
- Baby Monitor/Source Files/Utils/Randomizer.swift
- Baby MonitorTests/Mocks/RandomizerMock.swift
https://netguru.atlassian.net/browse/BM-671
Unified socket messages as is done on Android.
> [BM-671] Unify socket messages with Android

- Baby Monitor.xcodeproj/project.pbxproj
- Baby Monitor/Source Files/AppDependencies.swift
- Baby Monitor/Source Files/Modules/Onboarding/OnboardingCoordinator.swift
- Baby Monitor/Source Files/Services/Analytics/AnalyticsManager.swift
- Baby Monitor/Source Files/Services/Analytics/New Group/AnalyticsProtocol.swift
- Baby Monitor/Source Files/Services/Analytics/New Group1/FirebaseAnalyticsTracker.swift
- Baby Monitor/Source Files/Services/Analytics/Protocol/AnalyticsPropertyType.swift
- Baby Monitor/Source Files/Services/ServerService.swift
- Baby MonitorTests/Mocks/AnalyticsTrackerMock.swift
https://netguru.atlassian.net/browse/BM-673
Added set user properties analytics logic to the app, namely for new sound detection flow.
> [BM-673] Non-ML sound detection flow - analytics

- Baby Monitor/Source Files/Modules/Settings/BaseSettingsView.swift
https://netguru.atlassian.net/browse/BM-688
Update settings UI for smaller screen and safe area.
> [BM-688] User volume adjusting/customisation feature

- Baby Monitor/Source Files/Localizations/en.lproj/Localizable.strings
https://netguru.atlassian.net/browse/BM-670
Updated text for onboarding with the new information about sound detection modes.
> [BM-670] Non-ML voice detection flow: Onboarding adjustments

- .swiftlint.yml
- Baby Monitor/Source Files/Localizations/Localizable.swift
- Baby Monitor/Source Files/Modules/Onboarding/Pairing/Multiple Devices/Code/OnboardingCompareCodeViewModel.swift
- Baby Monitor/Source Files/Modules/Settings/ServerSettingsViewModel.swift
- Baby Monitor/Source Files/Services/MachineLearning/SpectrogramOp.swift
- Baby MonitorTests/Mocks/AudioBufferConverterMock.swift
- Podfile
- Podfile.lock
https://netguru.atlassian.net/browse/BM-693
Updated SwiftLint and fixed most of the warnings except one, which been extracted to another task.
> [BM-693] Update SwiftLint & fix new warnings
